# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Updated configuration (build.os)
build:
  os: ubuntu-20.04
  commands:
    - pip install -r requirements.txt
    - make html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt
